const express = require('express');
const bodyParser = require('body-parser');
const mysql = require("mysql");
const cors = require("cors");
require('dotenv').config();
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use('/uploads', express.static('uploads'));

const sliderRoutes = require('./routes/sliderRoutes');
const serviceRoutes = require('./routes/serviceRoutes');
const firestationRoutes = require('./routes/firestationRoutes');
const historyRoutes = require('./routes/historyRoutes');
const ceoRoutes = require('./routes/ceoRoutes');
const electedRoutes = require('./routes/electedRoutes');
const chiefRoutes = require('./routes/chiefRoutes');
const presidentRoutes = require('./routes/presidentRoutes');
const videosRoutes = require('./routes/videosRoutes');
const galleryRoutes = require('./routes/galleryRoutes');
const schoolRoutes = require('./routes/schoolRoutes');
const schoolImageRoutes = require('./routes/schoolImageRoutes');
const tenderRoutes = require('./routes/tenderRoutes');
const departmentRoutes = require('./routes/departmentRoutes');
const propertyHolderRoutes = require('./routes/propertyHolderRoutes');
const muncipalRoutes = require('./routes/muncipalRoutes');
const electricRoutes = require('./routes/electricRoutes');
const roadsRoutes = require('./routes/roadsRoutes');
const wardsRoutes = require('./routes/wardsRoutes');
const gardenRoutes = require('./routes/gardenRoutes');
const righttoservicesRoutes = require ('./routes/righttoservicesRoutes');
const pdfRToSRoutes = require('./routes/pdfRToSRoutes');
const citizenCharterRoutes = require('./routes/citizenCharterRoutes');
const AwardRoutes = require('./routes/AwardRoutes');
const awardImageRoutes = require('./routes/awardImageRoutes');
const GeneraladminaddyearRoutes = require('./routes/GeneraladminaddyearRoutes');
const GeneraladmindepartmentRoutes = require('./routes/GeneraladmindepartmentRoutes');
const NewsupdateRoutes = require('./routes/NewsupdateRoutes');
const PublicdescriptionRoutes = require('./routes/PublicdescriptionRoutes');
const WebsitelinkRoutes = require('./routes/WebsitelinkRoutes');
const userRoutes = require('./routes/userRoutes');
const pondRoutes = require('./routes/pondRoutes');
const hospitalRoutes = require('./routes/hospitalRoutes');
const censusRoutes = require('./routes/censusRoutes');
const functionRoutes = require('./routes/functionRoutes');
const healthDeptRoutes = require('./routes/healthDeptRoutes');
const sanitationRoutes = require('./routes/sanitationRoutes');
const treatmentRoutes = require('./routes/treatmentRoutes');
const litigationRoutes = require('./routes/litigationRoutes');
const healthPhotoRoutes = require('./routes/healthPhotoRoutes');
const mainMenuRoutes = require('./routes/mainMenuRoutes');
const contactRoutes = require('./routes/contactRoutes');
const loginRoutes = require('./routes/loginRoutes');
const visitorRoutes = require('./routes/visitorRoutes');
const pondImageRoutes = require('./routes/pondImageRoutes');
const conditionRoutes = require('./routes/conditionRoutes');
const policyRoutes = require('./routes/policyRoutes');
const emailRoutes = require('./routes/emailRoutes');
const publicationRoutes = require('./routes/publicationRoutes');
const downloadRoutes = require('./routes/downloadRoutes');
const developmentRoutes = require('./routes/developmentRoutes');
const developmentPdfRoutes = require('./routes/developmentPdfRoutes');
const departmentDataRoutes = require('./routes/departmentDataRoutes');
const departmentYearRoutes = require('./routes/departmentYearRoutes');
const notificationRoutes = require('./routes/notificationRoutes');
const adminNotificationRoutes = require('./routes/adminNotificationRoutes');
const notifyStatusRoutes = require('./routes/notifyStatusRoutes');
const ministerDetailRoutes = require('./routes/ministerDetailRoutes');
const citizenServicesRoutes = require('./routes/citizenServicesRoutes');
const homeVideosRoutes = require('./routes/homeVideosRoutes');
const currentUpdateRoutes = require('./routes/currentUpdateRoutes') ;
const umcNewsRoutes = require('./routes/umcNewsRoutes');
const eServicesRoutes = require('./routes/eServicesRoutes');
const initiativeRoutes = require('./routes/initiativeRoutes');
const bottomSliderRoutes = require('./routes/bottomSliderRoutes');
const homeServices2Routes = require('./routes/homeServices2Routes');
const homeGalleryRoutes = require('./routes/homeGalleryRoutes');
const quickLinksRoutes = require('./routes/quickLinksRoutes');
const helpLinksRoutes = require('./routes/helpLinksRoutes');
const onlineServicesRoutes = require('./routes/onlineServicesRoutes');
const informationRoutes = require('./routes/informationRoutes');
const projectRoutes = require('./routes/projectRoutes');
const homeService1Routes = require('./routes/homeService1Routes');
const portalServicesRoutes = require('./routes/portalServicesRoutes');
const emergencyServicesRoutes = require('./routes/emergencyServicesRoutes');
const administrativeRoutes = require('./routes/administrationRoutes');
const annualfinancialRoutes = require('./routes/annualfinancialRoutes');




app.use('/api', sliderRoutes);
app.use('/api', serviceRoutes);
app.use('/api', firestationRoutes);
app.use('/api', historyRoutes);
app.use('/api', ceoRoutes);
app.use('/api', electedRoutes);
app.use('/api', chiefRoutes);
app.use('/api', presidentRoutes);
app.use('/api', videosRoutes);
app.use('/api', galleryRoutes);
app.use('/api', schoolRoutes);
app.use('/api', schoolImageRoutes);
app.use('/api', tenderRoutes);
app.use('/api', departmentRoutes);
app.use('/api', propertyHolderRoutes);
app.use('/api', electricRoutes);
app.use('/api', roadsRoutes);
app.use('/api', muncipalRoutes);
app.use('/api', wardsRoutes);
app.use('/api', gardenRoutes);
app.use('/api', righttoservicesRoutes);
app.use('/api', pdfRToSRoutes);
app.use('/api', citizenCharterRoutes);
app.use('/api', AwardRoutes);
app.use('/api', GeneraladminaddyearRoutes);
app.use('/api', GeneraladmindepartmentRoutes);
app.use('/api', NewsupdateRoutes);
app.use('/api', PublicdescriptionRoutes);
app.use('/api', WebsitelinkRoutes);
app.use('/api', userRoutes);
app.use('/api', pondRoutes);
app.use('/api', hospitalRoutes);
app.use('/api', censusRoutes);
app.use('/api', functionRoutes);
app.use('/api', healthDeptRoutes);
app.use('/api', sanitationRoutes);
app.use('/api', treatmentRoutes);
app.use('/api', litigationRoutes);
app.use('/api', healthPhotoRoutes);
app.use('/api', mainMenuRoutes);
app.use('/api', awardImageRoutes);
app.use('/api', contactRoutes);
app.use('/api', loginRoutes);
app.use('/api', visitorRoutes);
app.use('/api', pondImageRoutes);
app.use('/api', conditionRoutes);
app.use('/api', policyRoutes);
app.use('/api', emailRoutes);
app.use('/api', publicationRoutes);
app.use('/api', downloadRoutes);
app.use('/api', developmentRoutes);
app.use('/api', developmentPdfRoutes);
app.use('/api', departmentDataRoutes);
app.use('/api', departmentYearRoutes);
app.use('/api', notificationRoutes);
app.use('/api', adminNotificationRoutes);
app.use('/api', notifyStatusRoutes);
app.use('/api', ministerDetailRoutes);
app.use('/api', citizenServicesRoutes);
app.use('/api', homeVideosRoutes);
app.use('/api', currentUpdateRoutes);
app.use('/api', umcNewsRoutes);
app.use('/api', eServicesRoutes);
app.use('/api', initiativeRoutes);
app.use('/api', bottomSliderRoutes);
app.use('/api', homeServices2Routes);
app.use('/api', homeGalleryRoutes);
app.use('/api', quickLinksRoutes);
app.use('/api', helpLinksRoutes);
app.use('/api', onlineServicesRoutes);
app.use('/api', informationRoutes);
app.use('/api', projectRoutes);
app.use('/api', homeService1Routes);
app.use('/api', portalServicesRoutes);
app.use('/api', emergencyServicesRoutes);
app.use('/api', administrativeRoutes);
app.use('/api', annualfinancialRoutes);




const PORT = process.env.PORT || 5011;
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});