// 📁 src/data/searchPages.js
export const searchablePages = [
    { title: "Sitemap", path: "/sitemap" },
    { title: "Home", path: "/" },
    { title: "Screen Reader Access", path: "/screen-reader-access" },
    { title: "Location", path: "/location" },
    { title: "History", path: "/history" },
    { title: "Commissioner", path: "/commissioner" },
    { title: "Tourism", path: "/tourism" },
    { title: "Additional Commissioner", path: "/additional-commissioner" },
    { title: "Assistant Commissioner", path: "/assistant-commissioner" },
    { title: "Deputy Commissioner", path: "/deputy-commissioner" },
    { title: "Administrative Structure", path: "/administrative-structure" },
    { title: "Administration", path: "/administration" },
    { title: "Agenda", path: "/agenda" },
    { title: "Annual Financial Statement", path: "/annual-financial-statement" },
    { title: "Budget", path: "/budget" },
    { title: "Committee", path: "/committee" },
    { title: "Elected Member", path: "/elected-member" },
    { title: "E-News", path: "/e-news" },
    { title: "Municipal Meeting", path: "/municipal-meeting" },
    { title: "Policies", path: "/policies" },
    { title: "Resolutions", path: "/resolutions" },
    { title: "Ward Office", path: "/ward-office" },
    { title: "Departments", path: "/departments" },
    { title: "Accounts Department", path: "/accounts-department" },
    { title: "Audit Department", path: "/audit-department" },
    { title: "Census Aadhar Center", path: "/census-aadhar-center" },
    { title: "Computer Department", path: "/computer-department" },
    { title: "Disaster Management Department", path: "/disaster-management-department" },
    { title: "Education Department", path: "/education-department" },
    { title: "Election Department", path: "/election-department" },
    { title: "Electrical Department", path: "/electrical-department" },
    { title: "Encroachment Department", path: "/encroachment-department" },
    { title: "Environment Department", path: "/environment-department" },
    { title: "Estate Department", path: "/estate-department" },
    { title: "Fire Department", path: "/fire-department" },
    { title: "Garden Department", path: "/garden-department" },
    { title: "General Administrative Department", path: "/general-administrative-department" },
    { title: "Handicap Welfare Scheme", path: "/handicap-welfare-scheme" },
    { title: "LBT Department", path: "/lbt-department" },
    { title: "Legal Department", path: "/legal-department" },
    { title: "Market and Licensing Department", path: "/market-and-licensing-department" },
    { title: "Medical Health Department", path: "/medical-health-department" },
    { title: "Municipal Secretary Department", path: "/municipal-secretary-department" },
    { title: "NULM Department", path: "/nulm-department" },
    { title: "Property Tax Department", path: "/property-tax-department" },
    { title: "Public Health Department", path: "/public-health-department" },
    { title: "Public Relationship Department", path: "/public-relationship-department" },
    { title: "Public Works Department", path: "/public-works-department" },
    { title: "Records Department", path: "/records-department" },
    { title: "Security Department", path: "/security-department" },
    { title: "Solid Waste Management Department", path: "/solid-waste-management-department" },
    { title: "Sports Department", path: "/sports-department" },
    { title: "Store Department", path: "/store-department" },
    { title: "Town Planning Department", path: "/town-planning-department" },
    { title: "Vehicle Department", path: "/vehicle-department" },
    { title: "Water Supply Department", path: "/water-supply-department" },
    { title: "Women and Child Development", path: "/women-and-child-department" },
    { title: "Circular", path: "/circular" },
    { title: "Property Tax Payment", path: "/property-tax-payment" },
    { title: "Birth Certificate", path: "/birth-certificate" },
    { title: "Death Certificate", path: "/death-certificate" },
    { title: "E-Tender", path: "/e-tender" },
    { title: "Photo Gallery", path: "/photo-gallery" },
    { title: "Video Gallery", path: "/video-gallery" },
    { title: "Recruitment", path: "/recruitment" },
    { title: "RTS Act 2015", path: "/rts-act-2015" },
    { title: "Press Note", path: "/press-note" },
    { title: "Solid Waste Management System", path: "/solid-waste-management-system" },
    { title: "Tenders and Quotations", path: "/tenders-and-quotations" },
    { title: "RTI", path: "/rti" },
    { title: "Proactive Disclosure", path: "/proactive-disclosure" },
    { title: "Sub RTI", path: "/sub-rti" },
    { title: "Terms and Conditions", path: "/terms-and-conditions" },
    { title: "Privacy Policy", path: "/privacy-policy" },
    { title: "Contact Us", path: "/contact-us" },
    { title: "Hyperlink Policy", path: "/hyperlink-policy" },
    { title: "Accessibility Statement", path: "/accessibility-statement" },
    { title: "Upcoming Projects", path: "/upcoming-projects" },
    { title: "Deputy Mayor Office", path: "/deputy-mayor-office" },
    { title: "Mayor Office", path: "/mayor-office" },
    { title: "Quotations", path: "/quotations" },
    { title: "Standing Committee", path: "/standing-committee" },
    { title: "Subject Committee", path: "/subject-committee" },
    { title: "Authorities", path: "/authorities" },
    { title: "Ward Committee", path: "/ward-committee" },
    { title: "Customer Support", path: "/customer-support" },
    { title: "Employee Information", path: "/employee-information" },


    { title: "साइट मॅप", path: "/sitemap" },
    { title: "मुखपृष्ठ", path: "/" },
    { title: "स्क्रीन वाचक प्रवेश", path: "/screen-reader-access" },
    { title: "स्थान", path: "/location" },
    { title: "इतिहास", path: "/history" },
    { title: "आयुक्त", path: "/commissioner" },
    { title: "पर्यटन", path: "/tourism" },
    { title: "अतिरिक्त आयुक्त", path: "/additional-commissioner" },
    { title: "सह आयुक्त", path: "/assistant-commissioner" },
    { title: "उप आयुक्त", path: "/deputy-commissioner" },
    { title: "प्रशासकीय संरचना", path: "/administrative-structure" },
    { title: "प्रशासन", path: "/administration" },
    { title: "वार्षिक आर्थिक विवरण", path: "/annual-financial-statement" },
    { title: "महापौर कार्यालय", path: "/mayor-office" },
    { title: "उपमहापौर कार्यालय", path: "/deputy-mayor-office" },
    { title: "ई-वृत्त पत्र", path: "/e-news" },
    { title: "निवडून आलेले सदस्य", path: "/elected-member" },
    { title: "महापालिका सभा", path: "/municipal-meeting" },
    { title: "स्थायी समिती", path: "/standing-committee" },
    { title: "विषय समिती", path: "/subject-committee" },
    { title: "उ. म. पा. अजेंडा", path: "/agenda" },
    { title: "उ. म. पा. प्राधिकरण", path: "/authorities" },
    { title: "उ. म. पा. अर्थसंकल्प", path: "/budget" },
    { title: "उ. म. पा. समिती", path: "/committee" },
    { title: "उ. म. पा. ठराव", path: "/resolutions" },
    { title: "प्रभाग कार्यालय", path: "/ward-office" },
    { title: "लेखा विभाग", path: "/accounts-department" },
    { title: "लेखा परिक्षण विभाग", path: "/audit-department" },
    { title: "माहिती व तंत्रज्ञान विभाग", path: "/computer-department" },
    { title: "आपत्ती व्यवस्थापन", path: "/disaster-management-department" },
    { title: "शिक्षण विभाग", path: "/education-department" },
    { title: "निवडणूक विभाग", path: "/election-department" },
    { title: "विद्युत विभाग", path: "/electrical-department" },
    { title: "अतिक्रमण विभाग", path: "/encroachment-department" },
    { title: "पर्यावरण विभाग", path: "/environment-department" },
    { title: "मालमत्ता विभाग", path: "/estate-department" },
    { title: "उद्यान विभाग", path: "/garden-department" },
    { title: "सामान्य प्रशासन विभाग", path: "/general-administrative-department" },
    { title: "दिव्यांग कल्याणकारी विभाग", path: "/handicap-welfare-scheme" },
    { title: "स्थानिक स्वराज्य संस्था विभाग", path: "/lbt-department" },
    { title: "विधी विभाग", path: "/legal-department" },
    { title: "बाजार आणि परवाना विभाग", path: "/market-and-licensing-department" },
    { title: "वैद्यकीय आरोग्य विभाग", path: "/medical-health-department" },
    { title: "सचिव कार्यालय", path: "/municipal-secretary-department" },
    { title: "राष्ट्रीय नागरी उपजीवीका अभियान विभाग", path: "/nulm-department" },
    { title: "मालमत्ता कर विभाग", path: "/property-tax-department" },
    { title: "सार्वजनिक आरोग्य विभाग", path: "/public-health-department" },
    { title: "जनसंपर्क विभाग", path: "/public-relationship-department" },
    { title: "सार्वजनिक बांधकाम विभाग", path: "/public-works-department" },
    { title: "सुरक्षा विभाग", path: "/security-department" },
    { title: "घनकचरा व्यवस्थापन विभाग", path: "/solid-waste-management-department" },
    { title: "क्रीडा विभाग", path: "/sports-department" },
    { title: "भांडार विभाग", path: "/store-department" },
    { title: "नगररचना विभाग", path: "/town-planning-department" },
    { title: "वाहन विभाग", path: "/vehicle-department" },
    { title: "पाणीपुरवठा विभाग", path: "/water-supply-department" },
    { title: "महिला व बाल कल्याण विभाग", path: "/women-and-child-department" },
    { title: "अभिलेखा विभाग", path: "/records-department" },
    { title: "जनगणना आणि आधार केंद्र", path: "/census-aadhar-center" },
    { title: "अग्निशमन विभाग", path: "/fire-department" },
    { title: "प्रभाग समिती विभाग", path: "/ward-office" },
    { title: "मालमत्ता कर", path: "/property-tax-payment" },
    { title: "जन्म प्रमाणपत्र", path: "/birth-certificate" },
    { title: "मृत्यू प्रमाणपत्र", path: "/death-certificate" },
    { title: "ई - निविदा प्रणाली", path: "/e-tender" },
    { title: "फोटो गॅलरी", path: "/photo-gallery" },
    { title: "व्हिडिओ गॅलरी", path: "/video-gallery" },
    { title: "भरती", path: "/recruitment" },
    { title: "महाराष्ट्र लोकसेवा हक्क अधिनियम २०१५", path: "/rts-act-2015" },
    { title: "प्रेस नोट", path: "/press-note" },
    { title: "घनकचरा व्यवस्थापन प्रणाली", path: "/solid-waste-management-system" },
    { title: "निविदा आणि कोटेशन", path: "/tenders-and-quotations" },
    { title: "माहितीचा अधिकार", path: "/rti" },
    { title: "सक्रिय प्रकटीकरण", path: "/proactive-disclosure" },
    { title: "सब RTI", path: "/sub-rti" },
    { title: "अटी व शर्ती", path: "/terms-and-conditions" },
    { title: "गोपनीयता धोरण", path: "/privacy-policy" },
    { title: "आमच्याशी संपर्क साधा", path: "/contact-us" },
    { title: "हायपरलिंक धोरण ", path: "/hyperlink-policy" },
    { title: "सुलभता विधान", path: "/accessibility-statement" },
    { title: "आगामी प्रकल्प", path: "/upcoming-projects" },
    { title: "उ.म.पा. कोटेशन", path: "/quotations" },
    { title: "स्थायी समिती", path: "/standing-committee" },
    { title: "विषय समिती", path: "/subject-committee" },
    { title: "उ.म.पा. प्राधिकरण", path: "/authorities" },
    { title: "प्रभाग समिती", path: "/ward-committee" },
    { title: "ग्राहक समर्थन", path: "/customer-support" },
    { title: "कर्मचारी माहिती", path: "/employee-information" }
];
